name: Run Tests and Lighthouse Performace Score

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn

      - run: yarn install

      - run: yarn test

  lighthouse-check:
    name: Check Lighthouse Performance Score
    runs-on: ubuntu-latest
    steps:
      - name: Run Lighthouse
        id: lighthouseCheck
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
          author: ${{ github.actor }}
          branch: ${{ github.ref }}
          urls: "https://sap-samples.github.io/devtoberfest-2021-frontend-coding-challenge/" ## todo, remove hard coded URL build based on pattern https://[owner].github.io/[repo]/

      - name: Comment PR
        # if: steps.lighthouseCheck.outputs.lighthouseCheckResults.performance > 75
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: 'Congrats, your web app achieved a performace score of  👋' });

      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minPerformanceScore: "2"

  assign-label:
    runs-on: ubuntu-latest
    name: Assign passing label
    needs:
      - run-test
      - lighthouse-check
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: passed
